feat: Complete stable software drivers for euclidean distance hardware accelerator

diff --git a/software/ACCEL_ASTAR/create-this-app b/software/ACCEL_ASTAR/create-this-app
--- a/software/ACCEL_ASTAR/create-this-app
+++ b/software/ACCEL_ASTAR/create-this-app
@@ -1,11 +1,11 @@
 #!/bin/bash
 #
-# This script creates the hello_world application in this directory.
+# This script creates the blank_project application in this directory.
 
 
 BSP_DIR=../ACCEL_ASTAR_bsp
 QUARTUS_PROJECT_DIR=../../
-NIOS2_APP_GEN_ARGS="--elf-name pathfinder.elf --set OBJDUMP_INCLUDE_SOURCE 1 --src-files src/**/*.cpp src/*.cpp"
+NIOS2_APP_GEN_ARGS="--elf-name accel_astar.elf --set OBJDUMP_INCLUDE_SOURCE 1 --src-files src/**/*.cpp src/*.cpp"
 
 # If script is launched from Windows through Windows Subsystem for Linux (WSL).  
 # The adjust-path macro converts absolute windows 
@@ -72,6 +72,26 @@ do
   esac
   shift
 done
+
+
+# Now we also need to go copy the sources for this application to the
+# local directory.
+find "${SOPC_KIT_NIOS2}/examples/software/blank_project/" -name '*.c' -or -name '*.h' -or -name 'hostfs*' | xargs -i cp -L {} ./ || {
+        echo "failed during copying example source files"
+        exit 1
+}
+
+find "${SOPC_KIT_NIOS2}/examples/software/blank_project/" -name 'readme.txt' -or -name 'Readme.txt' | xargs -i cp -L {} ./ || {
+        echo "failed copying readme file"
+}
+
+if [ -d "${SOPC_KIT_NIOS2}/examples/software/blank_project/system" ]
+then
+        cp -RL "${SOPC_KIT_NIOS2}/examples/software/blank_project/system" . || {
+                echo "failed during copying project support files"
+                exit 1
+        }
+fi
 
 chmod -R +w . || {
         echo "failed during changing file permissions"
